name: CI Workflow

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - develop
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Setup .NET
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0 # Updated to .NET 9.0

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore

    # Build the solution
    - name: Build solution
      run: dotnet build --no-restore --configuration Release

    # Run tests and collect code coverage
    - name: Run tests and collect code coverage
      run: |
        dotnet test --no-build --configuration Release \
          --collect:"XPlat Code Coverage" \
          --logger trx

    # Upload code coverage reports to Codecov
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: "**/coverage.cobertura.xml"
        flags: unittests
        name: codecov-umbrella

    # Publish test results (optional, for better PR experience)
    - name: Publish test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: '**/*.trx'

